coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 0%
        threshold: 0.5%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
