# cargo-deny configuration (minimal, v0.18+ compatible)
# Docs: https://embarkstudios.github.io/cargo-deny/

[licenses]
# Allow common OSS licenses used by your deps (MPL-2.0, MIT/Apache dual, Unicode, etc.)
allow = [
  "MIT", "MIT-0", "Apache-2.0",
  "BSD-2-Clause", "BSD-3-Clause",
  "ISC", "Zlib",
  "MPL-2.0",            # e.g. colored
  "Unicode-DFS-2016",   # ICU/Unicode data
  "Unicode-3.0",
  "Unlicense", "BSL-1.0", "CC0-1.0",
  "OpenSSL",
]

# Optional: you can add fine-grained exceptions like this if needed
# [[licenses.exceptions]]
# name = "some-crate"
# version = "*"
# license = "LGPL-3.0"
# justification = "Tooling-only; not distributed"

[bans]
# Keep warnings sane but not blocking for now
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
