# TIME Coin Masternode Configuration

[collateral]
# Minimum collateral tiers (in TIME)
bronze = 1_000
silver = 5_000
gold = 10_000
platinum = 50_000
diamond = 100_000

[rewards]
# Total masternode reward per block (in TIME)
block_reward = 95.0

# Reward multipliers by tier (slightly higher than linear)
[rewards.multipliers]
bronze = 1.0
silver = 5.2
gold = 10.5
platinum = 52.5
diamond = 105.0

[reputation]
# Starting reputation for new masternodes
starting_reputation = 0

# Minimum reputation to participate
min_reputation = -100

# Reputation changes
block_validated = 1
block_missed = -5
invalid_block = -20
offline = -10
voted = 2
slashed = -500

[heartbeat]
# Heartbeat interval (seconds)
interval = 60

# Maximum time offline before marking offline (seconds)
max_offline = 300

# Maximum offline time before slashing (24 hours)
max_offline_before_slash = 86400

[selection]
# Algorithm for masternode selection
algorithm = "weighted_random"  # or "round_robin", "deterministic"

# Minimum active masternodes required
min_active = 10

[slashing]
# Enable automatic slashing
enabled = true

# Slashing penalties (percentage of collateral)
missed_blocks = 1.0          # 1% for repeated missed blocks
invalid_block = 5.0          # 5% for invalid block
double_sign = 100.0          # 100% for double signing (severe)

# Cooldown before slashed funds returned (days)
cooldown_days = 30

[governance]
# Enable governance voting by masternodes
enabled = true

# Voting power multipliers (by tier)
[governance.voting_power]
bronze = 1
silver = 5
gold = 10
platinum = 50
diamond = 100

# Reward bonus for active voters
voting_bonus_percent = 5
