[masternode]
# Your masternode address
address = "TIME1your_address_here"

# Collateral transaction hash
collateral_tx = "your_tx_hash_here"

# Tier: "Community", "Verified", or "Professional"
tier = "Community"

# KYC status (for Verified and Professional tiers)
kyc_verified = false

# Network ports - 24-hour theme for TIME Coin
# Mainnet: 24000 (P2P), 24001 (RPC)
# Testnet: 24100 (P2P), 24101 (RPC)
[network]
listen_addr = "0.0.0.0:24000"
external_addr = "YOUR_PUBLIC_IP:24000"

[rpc]
bind = "0.0.0.0"
port = 24001

[performance]
# Target uptime percentage
target_uptime = 0.99

# Health check interval (seconds)
health_check_interval = 60
