# TIME Coin Treasury Configuration

[treasury]
# Fee percentage going to treasury (50%)
fee_percentage = 50

# Block reward going to treasury (5 TIME per block)
block_reward = 5.0

# Masternode block reward (95 TIME per block)
masternode_reward = 95.0

[proposals]
# Deposit required to submit proposal (in TIME)
submission_deposit = 100

# Discussion period before voting (in days)
discussion_period_days = 7

# Voting period (in days)
voting_period_days = 14

# Emergency proposal voting period (in days)
emergency_voting_days = 5

# Required approval percentage
approval_threshold = 60

# Required quorum percentage
quorum_threshold = 60

# Emergency proposal approval threshold
emergency_approval_threshold = 75

# Emergency proposal deposit (in TIME)
emergency_deposit = 500

[milestones]
# Grace period before first payout (in days)
grace_period_days = 30

# Maximum milestones per proposal
max_milestones = 10

# Minimum milestone amount (in TIME)
min_milestone_amount = 10

[security]
# Enable multi-signature for large withdrawals
multisig_enabled = true

# Threshold for requiring multi-sig (in TIME)
multisig_threshold = 10000

# Number of required signatures
multisig_required_signatures = 3

# Total number of signers
multisig_total_signers = 5

[reporting]
# Enable automatic financial reports
auto_reports = true

# Report frequency (daily, weekly, monthly, quarterly)
report_frequency = "monthly"

# Public transparency dashboard
public_dashboard = true

[limits]
# Maximum proposal amount (in TIME)
max_proposal_amount = 1000000

# Maximum total treasury spend per month (percentage)
max_monthly_spend_percent = 20

# Contingency buffer (percentage of balance)
contingency_buffer_percent = 10
