[package]
name = "time-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1"
sha2 = "0.10"
rand = "0.8"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
